# .github/workflows/docker-image.yml
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG="my-image-name:$(date +%s)"
        echo "Built image tag: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_TAG
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag the image for GHCR
      run: |
        REPOSITORY=${{ github.repository }}
        echo "Pushing to ghcr.io/$REPOSITORY:${{env.IMAGE_TAG#*:}}"
        docker tag ${{env.IMAGE_TAG}} ghcr.io/$REPOSITORY:${{env.IMAGE_TAG#*:}}
    - name: Push the Docker image
      run: |
        REPOSITORY=${{ github.repository }}
        docker push ghcr.io/$REPOSITORY:${{env.IMAGE_TAG#*:}}
