name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        LOCAL_BASE_IMAGE_NAME="my-image-name"
        TIMESTAMP_TAG=$(date +%s)
        FULL_LOCAL_TAG="${LOCAL_BASE_IMAGE_NAME}:${TIMESTAMP_TAG}"

        echo "Built full local tag: $FULL_LOCAL_TAG"
        echo "Extracted timestamp tag: $TIMESTAMP_TAG"

        echo "FULL_LOCAL_TAG=$FULL_LOCAL_TAG" >> $GITHUB_ENV
        echo "TIMESTAMP_TAG=$TIMESTAMP_TAG" >> $GITHUB_ENV

        docker build . --file Dockerfile --tag $FULL_LOCAL_TAG
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag the image for GHCR
      run: |
        REPOSITORY=${{ github.repository }}
        GHCR_TAG="ghcr.io/$REPOSITORY:${{ env.TIMESTAMP_TAG }}"
        echo "Tagging ${{ env.FULL_LOCAL_TAG }} as $GHCR_TAG"
        docker tag ${{ env.FULL_LOCAL_TAG }} $GHCR_TAG
    - name: Push the Docker image
      run: |
        REPOSITORY=${{ github.repository }}
        GHCR_TAG="ghcr.io/$REPOSITORY:${{ env.TIMESTAMP_TAG }}"
        echo "Pushing $GHCR_TAG"
        docker push $GHCR_TAG
